name: Rubocop
on: pull_request

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/cache@preview
        id: cache
        with:
          path: ~/local/rubies
          key: test-cache-1

      - uses: clupprich/ruby-build-action@master
        id: ruby
        with:
          ruby-version: 2.6.5
          cache-available: ${{ steps.cache.outputs.cache-hit == 'true' }}

      - name: Print version
        run: ruby --version

      - name: Install dependencies
        run: bundle install --without default development test

      - name: Run Rubocop
        run: rubocop
