name: Rubocop
on: pull_request

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/cache@preview
        id: cache
        with:
          path: ~/local/rubies
          key: 2.5.1
      - uses: clupprich/ruby-build-action@master
        id: ruby
        with:
          ruby-version: 2.5.1
          cache-available: ${{ steps.cache.outputs.cache-hit == 'true' }}
      - name: Print version
        run: ruby --version
      - name: Install dependencies
        run: bundle install
      - name: Run Rubocop
        run: rubocop

    # Runs a set of commands using the runners shell
    # - name: Run a multi-line script
      # run: |
        # echo Add other actions to build,
        # echo test, and deploy your project.
