name: Test
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.5', '2.6', '2.7'] # TODO add 3.0 compat , '3.0']
    name: Run specs with ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          path: vendor/bundle
          key: ${{ matrix.ruby }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.59.1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Setup sqlite3
        run: sudo apt-get install libsqlite3-dev

      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install

      - name: Migrate test database
        run: bin/rails db:migrate RAILS_ENV=test

      - name: Run rspec
        run: bin/rspec
